###################################################
#     __        __    __            __            #
#    |  \      |  \  |  \          |  \           #
#    | $$____  | $$  | $$ __    __ | $$____       #
#    | $$    \ | $$__| $$|  \  |  \| $$    \      #
#    | $$$$$$$\| $$    $$| $$  | $$| $$$$$$$\     #
#    | $$  | $$| $$$$$$$$| $$  | $$| $$  | $$     #
#    | $$__/ $$| $$  | $$| $$__/ $$| $$__/ $$     #
#    | $$    $$| $$  | $$ \$$    $$| $$    $$     #
#    \$$$$$$$  \$$   \$$  \$$$$$$  \$$$$$$$       #
#                                                 #
#           https://github.com/bradnn             #
#                    Made by:                     #
#               Braden (bradn#6668)               #
###################################################
spawn:
  world: world
  x: 500
  y: 150
  z: 500
  yaw: 10
checks:
  no inventory move: true
  no item drop: true
  no item pickup: true
selector:
  name: '&aSelector' # GUI Name
  size: 54
  inventory: # The item that appears in your hotbar
    name: '&aSelector'
    item: COMPASS
    slot: 3
items:
  '1':
    item: DIAMOND_BLOCK
    name: '&a&lServer 1'
    slot: 0
    lore:
      - '&aLine 1'
      - ' '
      - '&7example.net'
    command: 'server server1'
visibility: # Player visibility toggle
  enabled: true
  item slot: 8
  visible:
    dye color: LIME
    name: '&fPlayers: &aVisible'
  invisible:
    dye color: GRAY
    name: '&fPlayers: &7Invisible'
join messages: # Messages sent when joining the server
  enabled: true
  join message: '&7+ &b{player}'
  leave message: '&7- &b{player}'
tablist: # The header and footer of the playerlist
  enabled: true
  header:
    - '&b&lbHub'
    - '&fExample Header'
  footer:
    - '&bgithub.com/bradnn'
    - '&fCheck me out ^^'
ender butt: # Throwable enderpearl that you ride
  enabled: true
  name: '&aEnder Butt'
  item slot: 5
double jump: # Double jump
  enabled: true
join sound: # Sound played when joining the server
  enabled: true
  sound: LEVEL_UP
join title: # Title send when joining ths erver
  enabled: true
  title: '&b&lWELCOME'
  subtitle: '&f{player}'
join motd: # Message sent to the player when joining the server
  enabled: true
  message:
    - '&7Thank you for downloading &bbHub&7, &f{player}&7!'
    - '&b&l* &fhttps://github.com/bradnn'
    - '&b&l* &fbradn#6668'
    - '&b&l* &fEdit this message in the config.'